on:
  push:
    branches: [master, main]
    paths:
      - README.md

name: docpress

jobs:
  docpress:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Packages
        run: |
          npm install --save-dev --save-exact docpress
      - name: Build Docs
        run: ./node_modules/.bin/docpress build
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages 
          folder: _docpress
